services:
  db:
    image: "postgres:17"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - ./db:/var/lib/postgresql/data

  app:
    build:
     context: .
     args:
      SECRET_KEY: ${SECRET_KEY}
    env_file: .env

    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    depends_on:
      - db
    ports:
      - "8000:8000"