# Generated by Django 5.1 on 2024-08-30 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_rename_question_choice_question_text_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choice",
            old_name="question_text",
            new_name="question",
        ),
    ]
